//images
var Img = {};
Img.map = new Image();
Img.map.src = 'img/map/map.png';
Img.arrowRight = new Image();
Img.arrowRight.src = 'img/arrow_right.png';
Img.arrowLeft = new Image();
Img.arrowLeft.src = 'img/arrow_left.png';
Img.arrowUp = new Image();
Img.arrowUp.src = 'img/arrow_up.png';
Img.arrowSpd = new Image();
Img.arrowSpd.src = 'img/arrow_speed.png';
Img.cancel = new Image();
Img.cancel.src = 'img/cancel.png';
Img.heart = new Image();
Img.heart.src = 'img/heart.png';
Img.coin = new Image();
Img.coin.src = 'img/coin_gold.png';
Img.coinAnimated = new Image();
Img.coinAnimated.src = 'img/coins_gold.png';

Img.skeleton = new Image();
Img.skeleton.src = 'img/creep/skeleton.png';
Img.dino = new Image();
Img.dino.src = 'img/creep/dino.png';
Img.golem = new Image();
Img.golem.src = 'img/creep/golem.png';
Img.snake = new Image();
Img.snake.src = 'img/creep/snake.png';
Img.zombie = new Image();
Img.zombie.src = 'img/creep/zombie.png';
Img.eye = new Image();
Img.eye.src = 'img/creep/eye.png';
Img.flame = new Image();
Img.flame.src = 'img/creep/flame.png';
Img.ghost = new Image();
Img.ghost.src = 'img/creep/ghost.png';
Img.jellyfish = new Image();
Img.jellyfish.src = 'img/creep/jellyfish.png';
Img.plant = new Image();
Img.plant.src = 'img/creep/plant.png';
Img.slime = new Image();
Img.slime.src = 'img/creep/slime.png';

Img.tower = new Image();
Img.tower.src = 'img/tower/tower_round.png';
Img.seekingTower = new Image();
Img.seekingTower.src = 'img/tower/tower_round_flag.png'
Img.wall = new Image();
Img.wall.src = 'img/tower/tower_square.png';
Img.pyramid = new Image();
Img.pyramid.src = 'img/tower/pyramid.png';

Img.ammo = new Image();
Img.ammo.src = 'img/projectile/energy_ball.png';
Img.pyramidAmmo = new Image();
Img.pyramidAmmo.src = 'img/projectile/sphere-12.png';
Img.seekingAmmo = new Image();
Img.seekingAmmo.src = 'img/projectile/sphere-10.png';